//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoclipuriYTB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResurseEntities : DbContext
    {
        public ResurseEntities()
            : base("name=ResurseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorii> Categorii { get; set; }
        public virtual DbSet<Taguri> Taguri { get; set; }
        public virtual DbSet<Videoclipuri> Videoclipuri { get; set; }
    }
}
