//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoclipuriYTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taguri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taguri()
        {
            this.Videoclipuri = new HashSet<Videoclipuri>();
        }
    
        public int Id_Tag { get; set; }
        public string Tag { get; set; }
        public int Categorie { get; set; }
    
        public virtual Categorii Categorii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Videoclipuri> Videoclipuri { get; set; }
    }
}
