//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoclipuriYTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videoclipuri
    {
        public int Id_Videoclip { get; set; }
        public string Link { get; set; }
        public int Tag { get; set; }
    
        public virtual Taguri Taguri { get; set; }
    }
}
